### PR TITLE
Reuse generated key pair

### PR DESCRIPTION
**Pull request by ertwroc**
Improve performance by reusing generated key pair (previously new key pair was generated for each request what is very costly operation).

### CODE REVIEW

**Comment by schaabs** [comment]
@ertwroc thank you for the contribution.  I've slightly modified your fix to keep it backwards compatible, as well as eliminate the key pair generation completely in the case where the vault doesn't support message security.   I submitted a new PR based off your fix here https://github.com/Azure/azure-keyvault-java/pull/78.  PTAL.

**Comment by schaabs** [comment]
@ertwroc if you'd prefer we can add the changes from #78 into this PR. Otherwise we can close this PR and use #78 to merge the fix.

**Comment by ertwroc** [comment]
@schaabs thanks for taking care of this. #78 looks fine for me and if you don't mind would be nice if you add these changes to this PR.

**Comment by schaabs** [comment]
@ertwroc No problem, but you'll have to pull the changes from my branch into yours and push them to your remote branch since I don't have access to push changes to your branch.  My branch is based off your cache_client_encryption_key branch so  there shouldn't be any conflicts or merge required.

To pull my changes:

    git remote add schaabs  https://github.com/schaabs/azure-keyvault-java.git
    git pull schaabs cache_client_encryption_key 

Let me know if you have any problems.  Once you've included the changes into this PR I'll merge it and close mine.  Thanks again!

**Comment by ertwroc** [comment]
@schaabs It's done.

**Comment by schaabs** [comment]
@ertwroc This fix has been released in [1.2.0](https://github.com/Azure/azure-keyvault-java/releases/tag/1.2.0), and is available via mvn, https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault/1.2.0

**Pull request merged**
